req-io/req.io

- CONTRIBUTING.md
- README.md
This is associated to the issue #11
> Add CONTRIBUTING.md for req.io

- src/components/AppBody/index.tsx
- src/components/RequestHeadersPanel/index.tsx
- src/components/RequestHeadersPanel/types.ts
- src/components/RequestPanel/index.tsx
- src/components/RequestPanel/types.ts
This implementation allows users to edit the default header key and value edit and trigger the request with this updated header
> [ #14 ] Implementation to make default headers key and value editable

- src/components/RequestHeadersPanel/index.scss
- src/components/RequestHeadersPanel/index.tsx
This is an implementation based on the issue #15 , added the ability to add custom request headers
> [ #15 ] Implemented ability to add custom request headers

- package.json
- src/components/Editor/index.tsx
- src/components/ResponsePanel/index.scss
- src/components/ResponsePanel/index.tsx
- src/components/ResponsePanel/types.ts
Implemented a response navbar with preview and raw as items with a simple raw data viewer.
This is associated to the issue #16 
Previews of the implementation,
> [ #16 ] Implemented navbar for response panel

- .talismanrc
- src/components/AppBody/index.tsx
Resolved missing imports caused by merge conflict 
issue number #17
> [17] | Pravitha | Resolved missing imports caused by merge conflict

- src/api/rest.ts
- src/components/AppBody/index.tsx
implementation for the issue #19 ,to add support for delete request with url.
> [19] | Pravitha | Add support for DELETE request with URL

- src/components/AppBody/index.tsx
- src/components/Editor/index.tsx
- src/components/RequestPanel/index.tsx
- src/components/RequestPanel/types.ts
Fixed the json body getting reseted when switches to header tab
This is an bug fix based on the issue #43
> [ #43 ] | Anil | Fixed the json body getting reseted when switches to header tab

- src/components/Editor/index.tsx
- src/components/Editor/types.ts
This is implementation based on issue #45 and #49
Preview of the implementation below
> [#45] | soft wrap enabled for json editor

- README.md
Updated the readme to display contributors list. This is the implementation of the issue #45
Check below for the screenshot
> [#45] | Display contributors in readme document

- .talismanrc
- src/components/UrlPanel/index.tsx
Added feature to trigger request with enter key press from url panel. This is an implementation based on the issue #36
> [#36] | Trigger request with enter key press from url panel

- .circleci/config.yml
- package.json
Added basic Circle CI workflow with lint and typecheck jobs.
> Added basic Circle CI workflow

- src/api/rest.ts
- src/api/statusCodes.ts
- src/api/types.ts
- src/components/AppBody/index.tsx
- src/components/Editor/index.tsx
- src/components/Editor/types.ts
- src/components/Navbar/index.tsx
- src/components/Navbar/types.ts
- src/components/RequestHeadersPanel/index.tsx
- src/components/RequestHeadersPanel/types.ts
- src/components/RequestPanel/index.tsx
- src/components/RequestPanel/types.ts
- src/components/ResponsePanel/index.tsx
- src/components/ResponsePanel/types.ts
- src/components/UrlPanel/index.tsx
- src/components/UrlPanel/types.ts
Fixed all the existing lint and typecheck errors based on the CI workflow checks
Issue: #55
> [ #55 ] | Anil | Fixed all lint and typecheck errors

- .circleci/config.yml
Associated to #55 
Added test job into the main CI workflow
> [ 55 ] | Anil | Added test job to the CI workflow

- src/components/Editor/index.scss
- src/components/ResponsePanel/index.scss
**Changes made as part of this PR**
- Updated Request body scrollbar style
- Updated Response raw view and preview scrollbar style
- Removed unwanted horizontal scrollbar for Response raw view
**Updated view screenshot**
> [ #83 ] [ Anil ] Enhanced Request body, Response raw and preveiw scrollbar styling

- src/components/UrlPanel/index.scss
- src/components/UrlPanel/index.tsx
Added colors to the request method as follows,
GET - #10B95F
POST - #FFC107
PUT - #007BFF
PATCH - #6366F1
DELETE - #DC3545
When user selects a parti
#34
> [ #34 ] [ Pravitha ] Added colors to the selected request method 

- src/components/RequestHeadersPanel/index.tsx
Removed the header row from request headers table
> [#90] | [Ajay] | Removed the header row from request headers table

- src/components/RequestParamsPanel/index.tsx
Added empty placeholder for the request params
> [#87] Add an empty placeholder to request params

- src/components/AppBody/index.tsx
- src/components/CustomDropdown/index.scss
- src/components/CustomDropdown/index.tsx
- src/components/CustomDropdown/types.ts
- src/components/Dropdown/index.scss
- src/components/Dropdown/index.tsx
- src/components/Dropdown/types.ts
- src/components/RequestPanel/index.tsx
- src/components/UrlPanel/index.scss
- src/components/UrlPanel/index.tsx
- src/components/UrlPanel/types.ts
- tests/components/CustomDropdown.test.tsx
- tests/components/Dropdown.test.tsx
Implemented a reusable Dropdown component matching the application theme and used it for the request method selection, attaching the screenshots below.
> [ #30 ] [ Anil ] Implemented Dropdown matching to application theme and used for request method selection

- yarn.lock
The issue was with some dependency version mismatch associated to vitest, I have updated yarn lock file to fix those vitest dependency issues.
> [ #119 ] [ Anil ] | Fixed test coverage run issue

- tests/components/Spinner.test.tsx
Added test file for Spinner component : 
✓ renders spinner container and spinner div
✓ renders only the default structure
> Added test for spinner

- src/components/AppBody/index.tsx
- src/components/PaneSplitter/index.tsx
- src/components/RequestPanel/index.tsx
- src/components/ResponsePanel/index.tsx
- src/components/UrlPanel/index.tsx
- tests/components/AppBody.test.tsx
Added tests for AppBody component, changed some of the source files for adding dats-testid field to the component for testing
> [ #85 ] [ Aman ] Adds tests for AppBody component
